name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      EXCEL_BASEURL: ${{ secrets.EXCEL_BASEURL }}
      EXCEL_USER: ${{ secrets.EXCEL_USER }}
      EXCEL_PASSWORD: ${{ secrets.EXCEL_PASSWORD }}
      EXCEL_STORAGE_STATE: ${{ secrets.EXCEL_STORAGE_STATE }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Restore storageState.json
        run: |
          echo "$EXCEL_STORAGE_STATE" > storageState.json
          echo "=== storageState.json created ==="
          ls -la storageState.json
          echo "=== Preview of storageState.json (first 200 chars) ==="
          head -c 200 storageState.json
          echo ""
          echo "=== End of preview ==="

          # Walidacja – jeśli plik pusty, przerwij job
          if [ ! -s storageState.json ]; then
            echo " ERROR: storageState.json is empty!"
            exit 1
          fi

      - name: Run Playwright tests
        run: npm run test:all

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

      - name: Upload Playwright traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: test-results/
